---
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-07d0cf3af28718ef8
      InstanceType: t2.micro
      KeyName: amazonKeys
